import Images from "./images"

const Icons = {
 back :  require("../assets/icons/back.png"),
 order : require("../assets/icons/order.png"),
 notification :require("../assets/icons/bell.png")  ,
 bell :require("../assets/icons/bell2.png")  ,
 home : require("../assets/icons/home.png"),
 login : require("../assets/icons/signin.jpg"),
 signup : require("../assets/icons/signup.jpg"),
 car : require("../assets/icons/car.png"),
 cutlery : require("../assets/icons/cutlery.png"),
 donut : require("../assets/icons/donut.png"),
 drink : require("../assets/icons/drink.png"),
 fire : require("../assets/icons/fire.png"),
 fries : require("../assets/icons/fries.png"),
 hamburger : require("../assets/icons/hamburger.png"),
 hotdog : require("../assets/icons/hotdog.png"),
 like : require("../assets/icons/like.png"),
 list : require("../assets/icons/list.png"),
 location : require("../assets/icons/location.png"),
 master_card : require("../assets/icons/mastercard.png"),
 nearby : require("../assets/icons/nearby.png"),
 noodle : require("../assets/icons/noodle.png"),
 pin : require("../assets/icons/pin.png"),
 pizza : require("../assets/icons/pizza.png"),
 red_pin : require("../assets/icons/red-pin.png"),
 rice_bowl : require("../assets/icons/rice-bowl.png"),
 salad : require("../assets/icons/salad.png"),
 search : require("../assets/icons/search.png"),
 basket : require("../assets/icons/shopping-basket.png"),
 star : require("../assets/icons/star.png"),
 sushi : require("../assets/icons/sushi.png"),
 user : require("../assets/icons/user.png"), 
}

export default Icons;