const Images = {
     avatar_1 : require("../assets/images/avatar-1.jpg"),
     avatar_2 : require("../assets/images/avatar-2.jpg"),
     avatar_3 : require("../assets/images/avatar-3.jpg"),
     avatar_4 : require("../assets/images/avatar-4.jpg"),
     avatar_5 : require("../assets/images/avatar-5.jpg"),
     baked_fries : require("../assets/images/baked-fries.jpg"),
     burger_restaurant_1 : require("../assets/images/burger-restaurant.jpg"),
     burger_restaurant_2 : require("../assets/images/burger-restaurant-2.jpg"),
     chicago_hot_dog : require("../assets/images/chicago-hot-dog.jpg"),
     crispy_chicken_burger : require("../assets/images/crispy-chicken-burger.jpg"),
     fries_restaurant : require("../assets/images/fries-restaurant.jpg"),
     hawaiian_pizza : require("../assets/images/hawaiian-pizza.jpg"),
     honey_mustard_chicken_burger : require("../assets/images/honey-mustard-chicken-burger.jpg"),
     hot_dog_restaurant : require("../assets/images/hot-dog-restaurant.jpg"),
     ice_kacang : require("../assets/images/ice-kacang.jpg"),
     japanese_restaurant : require("../assets/images/japanese-restaurant.jpg"),
     kek_lapis_shop : require("../assets/images/kek-lapis-shop.jpg"),
     kek_lapis : require("../assets/images/kek-lapis.jpg"),
     kolo_mee : require("../assets/images/kolo-mee.jpg"),
     tomato_pasta : require("../assets/images/tomato-pasta.jpg"),
     nasi_briyani_mutton : require("../assets/images/nasi-briyani-mutton.jpg"),
     nasi_lemak : require("../assets/images/nasi-lemak.jpg"),
     noodle_shop : require("../assets/images/noodle-shop.jpg"),
     pizza_restaurant : require("../assets/images/pizza-restaurant.jpg"),
     pizza : require("../assets/images/pizza.jpg"),
     salad : require("../assets/images/salad.jpg"),
     sarawak_laksa : require("../assets/images/sarawak-laksa.jpg"),
     sushi : require("../assets/images/sushi.jpg"),
     teh_c_peng : require("../assets/images/teh-c-peng.jpg"),
     splashFood: require("../assets/images/splashfood.png"),
     splashLogo : require("../assets/images/splashLogo.png"),
     mama : require("../assets/images/mama.png"),
     hamburger : require("../assets/images/hamburger.png"),
     bell : require("../assets/images/bell.png"),
     food1 : require("../assets/images/food1.jpg"),
     food2 : require("../assets/images/food2.jpg"),
     food3 : require("../assets/images/food3.jpg"),
     food4 : require("../assets/images/food4.jpg"),
     food5 : require("../assets/images/food5.jpg"),
     closecross : require("../assets/images/close-cross.png"),
     paytm : require("../assets/images/paytm.png"),
     gpay : require("../assets/images/gpay.png"),
     cash : require("../assets/images/cash.png"),
};

export default Images;